### ISSUE TITLE
Featured request: Different policy for different user groups

### ISSUE THREAD

**Issue by Coysh** [Rias500/craft-password-policy#5]
Would be helpful in my use case - I want users to have a strong password, but administrators (my colleagues) to have an even stronger password.

**Comment by Rias500** [comment]
I don't see this as a useful feature to be honest, passwords should always be strong enough, I'd say set a limit for your users and educate your colleagues enough that they want to use stronger passwords ;)

If you really need this you are free to open a PR that implements it
